import { expect, describe, test, beforeAll, afterAll } from "bun:test";
import { $ } from "bun";
import * as fs from "node:fs";
import * as path from "node:path";

const testDir = import.meta.dir;
const sampleDir = path.resolve(testDir, "sample");
const cliPath = path.resolve(testDir, "../src/index.ts");
const configPath = path.resolve(sampleDir, "p9s.config.ts");
const outputPath = path.resolve(testDir, "output.sql");

describe("p9s CLI", () => {
  afterAll(() => {
    if (fs.existsSync(outputPath)) {
      fs.unlinkSync(outputPath);
    }
  });

  test("shows help with --help flag", async () => {
    const result = await $`bun run ${cliPath} --help`.text();

    expect(result).toContain("p9s");
    expect(result).toContain("Permission Tree CLI");
    expect(result).toContain("postgres");
    expect(result).toContain("--version");
    expect(result).toContain("--help");
  });

  test("shows version with --version flag", async () => {
    const result = await $`bun run ${cliPath} --version`.text();

    expect(result.trim()).toBe((await Bun.file(path.resolve(testDir, "../package.json")).json()).version);
  });

  test("shows postgres subcommand help", async () => {
    const result = await $`bun run ${cliPath} postgres --help`.text();

    expect(result).toContain("postgres");
    expect(result).toContain("generate");
    expect(result).toContain("PostgreSQL");
  });

  test("shows postgres generate help", async () => {
    const result = await $`bun run ${cliPath} postgres generate --help`.text();

    expect(result).toContain("Generate PostgreSQL migration SQL");
    expect(result).toContain("--config");
    expect(result).toContain("--output");
  });

  test("generates SQL migration from config file", async () => {
    if (fs.existsSync(outputPath)) {
      fs.unlinkSync(outputPath);
    }

    const result = await $`bun run ${cliPath} postgres generate --config ${configPath} --output ${outputPath}`.text();

    expect(result).toContain("Loading configuration");
    expect(result).toContain("Generating PostgreSQL migration");
    expect(result).toContain("Migration written to");

    expect(fs.existsSync(outputPath)).toBe(true);

    const sql = fs.readFileSync(outputPath, "utf-8");

    expect(sql).toContain("resource_node");
    expect(sql).toContain("role_node");
    expect(sql).toContain("assignment_edge");
    expect(sql).toContain("app_user");
    expect(sql).toContain("folder");
    expect(sql).toContain("bit(64)");
  });

  test("configures graph writers from a Drizzle schema", async () => {
    const drizzleSchemaPath = path.resolve(testDir, "../../drizzle/test/sample/schema1.ts");
    const drizzleOutputPath = path.resolve(testDir, "drizzle-output.json");
    try {
      await $`bun run ${cliPath} drizzle configure --schema ${drizzleSchemaPath} --output ${drizzleOutputPath} --users app_user --graph-writers app_backend,migrator`.text();
      const config = JSON.parse(fs.readFileSync(drizzleOutputPath, "utf-8"));

      expect(config.engine.users).toEqual(["app_user"]);
      expect(config.engine.graphWriters).toEqual(["app_backend", "migrator"]);
    } finally {
      fs.rmSync(drizzleOutputPath, { force: true });
    }
  });

  test.skipIf(!process.env.P9S_TEST_DATABASE_URL)("tells whether the database ran the migration of the config", async () => {
    const rootUrl = process.env.P9S_TEST_DATABASE_URL!;
    const databaseName = `p9s_cli_${Date.now()}`;
    const url = new URL(rootUrl);
    url.pathname = `/${databaseName}`;
    const statusConfigPath = path.resolve(testDir, "status.config.json");
    const statusOutputPath = path.resolve(testDir, "status.sql");
    const config = (bits: number) => ({
      engine: { users: ["app_user"], permission: { bitmap: { size: bits } }, authentication: { getCurrentUserId: "get_current_user_id", setting: "app.user_id" }, id: { mode: "integer" } },
      tables: [{ name: "folder", isResource: true, permission: { app_user: { select: 0, insert: 1, update: 2, delete: 3 } } }],
    });
    const status = () => $`bun run ${cliPath} postgres status --config ${statusConfigPath} --database-url ${url.toString()}`.nothrow().quiet();
    const pg = (await import("pg")).default;
    const run = async (connectionString: string, text: string) => {
      const client = new pg.Client({ connectionString });
      await client.connect();
      try { await client.query(text); } finally { await client.end(); }
    };
    await run(rootUrl, `create database ${databaseName}`);
    try {
      await run(url.toString(), `
        do $$ begin create role app_user; exception when duplicate_object then null; end $$;
        create table folder (id integer primary key generated by default as identity);`);
      fs.writeFileSync(statusConfigPath, JSON.stringify(config(64)));

      const missing = await status();
      expect(missing.exitCode).toBe(1);
      expect(missing.stdout.toString()).toContain("No p9s migration");

      await $`bun run ${cliPath} postgres generate --config ${statusConfigPath} --output ${statusOutputPath}`.quiet();
      await run(url.toString(), fs.readFileSync(statusOutputPath, "utf-8"));
      const current = await status();
      expect(current.exitCode).toBe(0);
      expect(current.stdout.toString()).toContain("Up to date");

      fs.writeFileSync(statusConfigPath, JSON.stringify(config(32)));
      const outdated = await status();
      expect(outdated.exitCode).toBe(1);
      expect(outdated.stdout.toString()).toContain("Outdated");
    } finally {
      fs.rmSync(statusConfigPath, { force: true });
      fs.rmSync(statusOutputPath, { force: true });
      await run(rootUrl, `drop database if exists ${databaseName} with (force)`);
    }
  });

  test("fails gracefully when no config file found", async () => {
    const fakeConfig = path.resolve(testDir, "nonexistent.config.ts");

    try {
      await $`bun run ${cliPath} postgres generate --config ${fakeConfig}`.text();
      expect(true).toBe(false);
    } catch (error: any) {
      expect(error.stderr.toString()).toContain("ENOENT");
    }
  });

  test("shows validate subcommand help", async () => {
    const result = await $`bun run ${cliPath} validate --help`.text();

    expect(result).toContain("validate");
    expect(result).toContain("config");
    expect(result).toContain("Validate configuration file");
  });

  test("shows validate config help", async () => {
    const result = await $`bun run ${cliPath} validate config --help`.text();

    expect(result).toContain("Validate the p9s configuration file");
    expect(result).toContain("--config");
    expect(result).toContain("--strict");
  });

  test("validates config file", async () => {
    const result = await $`bun run ${cliPath} validate config --config ${configPath}`.text();

    expect(result).toContain("Loading configuration");
    expect(result).toContain("Validating configuration");
  });

  test("validate fails gracefully when no config file found", async () => {
    const fakeConfig = path.resolve(testDir, "nonexistent.config.ts");

    try {
      await $`bun run ${cliPath} validate config --config ${fakeConfig}`.text();
      expect(true).toBe(false);
    } catch (error: any) {
      expect(error.stderr.toString()).toContain("ENOENT");
    }
  });
});
