# Generated by Django 6.1.2 on 2026-10-09 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'teams',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('body', models.TextField(db_default='', default='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DB_CASCADE, to='documents.project')),
            ],
            options={
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('pk', models.CompositePrimaryKey('team_id', 'user_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DB_CASCADE, to='documents.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DB_CASCADE, to='documents.user')),
            ],
            options={
                'db_table': 'team_members',
            },
        ),
        migrations.CreateModel(
            name='ProjectShare',
            fields=[
                ('pk', models.CompositePrimaryKey('project_id', 'team_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('access', models.TextField(choices=[('viewer', 'viewer'), ('editor', 'editor'), ('owner', 'owner')])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DB_CASCADE, to='documents.project')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DB_CASCADE, to='documents.team')),
            ],
            options={
                'db_table': 'project_shares',
                'constraints': [models.CheckConstraint(condition=models.Q(('access__in', ['viewer', 'editor', 'owner'])), name='project_shares_access_check')],
            },
        ),
        migrations.CreateModel(
            name='DocumentShare',
            fields=[
                ('pk', models.CompositePrimaryKey('document_id', 'user_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('access', models.TextField(choices=[('viewer', 'viewer'), ('editor', 'editor')])),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.DB_CASCADE, to='documents.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DB_CASCADE, to='documents.user')),
            ],
            options={
                'db_table': 'document_shares',
                'constraints': [models.CheckConstraint(condition=models.Q(('access__in', ['viewer', 'editor'])), name='document_shares_access_check')],
            },
        ),
    ]
