import { expect, test } from 'bun:test'
import { getCompleteConfig, getCompleteNamingConfig } from './configuration';

test('Default Configuration', () => {
  const completeConfig = getCompleteConfig({
    engine: {
      users: ["user1"],
    },
    tables: [{
      name: "human_user",
      isRole: true,
      roleId: "role_id",
    }, {
      name: "blog_post",
      isResource: true,
      resourceId: "resource_id",
      permission: {
        user1: {
          select: 1
        }
      }
    }]
  });
  const naming = getCompleteNamingConfig(completeConfig);
  expect(naming).toMatchInlineSnapshot(`
    {
      "assignment": {
        "combinedEdgeDeleteTrigger": "20_assignment_edge_none_delete_trigger",
        "combinedEdgeDeleteTriggerFunction": "assignment_edge_none_delete_trigger_function",
        "combinedEdgeInsertTrigger": "20_assignment_edge_none_insert_trigger",
        "combinedEdgeInsertTriggerFunction": "assignment_edge_none_insert_trigger_function",
        "combinedEdgeUpdateTrigger": "20_assignment_edge_none_update_trigger",
        "combinedEdgeUpdateTriggerFunction": "assignment_edge_none_update_trigger_function",
        "disableTriggerFunction": "assignment_trigger_disable",
        "edge": "assignment_edge",
        "edgeCache": "assignment_edge_cache",
        "edgeCacheBackfill": "assignment_edge_cache_backfill",
        "edgeCachePkey": "assignment_edge_cache_pkey",
        "edgeCacheResourceFkey": "assignment_edge_cache_resource_fkey",
        "edgeCacheResourceIdIndex": "assignment_edge_cache_resource_id_index",
        "edgeCacheRoleFkey": "assignment_edge_cache_role_fkey",
        "edgeCacheRoleIdIndex": "assignment_edge_cache_role_id_index",
        "edgeCacheView": "assignment_edge_cache_view",
        "edgeDeleteTrigger": "10_assignment_edge_delete_trigger",
        "edgeDeleteTriggerFunction": "assignment_edge_delete_trigger_function",
        "edgeInsertTrigger": "10_assignment_edge_insert_trigger",
        "edgeInsertTriggerFunction": "assignment_edge_insert_trigger_function",
        "edgePkey": "assignment_edge_pkey",
        "edgeResourceIdIndex": "assignment_edge_resource_id_index",
        "edgeRoleIdIndex": "assignment_edge_role_id_index",
        "edgeUpdateTrigger": "10_assignment_edge_update_trigger",
        "edgeUpdateTriggerFunction": "assignment_edge_update_trigger_function",
        "enableTriggerFunction": "assignment_trigger_enable",
        "name": "assignment",
        "permission": "permission",
        "resourceFkey": "assignment_edge_resource_fkey",
        "resourceId": "resource_id",
        "roleFkey": "assignment_edge_role_fkey",
        "roleId": "role_id",
      },
      "backfill": "backfill",
      "cache": "cache",
      "child": "child",
      "compute": "compute",
      "delete": "delete",
      "disable": "disable",
      "edge": "edge",
      "enable": "enable",
      "fkey": "fkey",
      "function": "function",
      "id": "id",
      "index": "index",
      "insert": "insert",
      "node": "node",
      "orBitmap": "or_bitmap_128",
      "parent": "parent",
      "permission": "permission",
      "pkey": "pkey",
      "policy": "policy",
      "prefix": "",
      "recursive": "recursive",
      "refresh": "refresh",
      "resource": {
        "childFkey": "resource_edge_child_fkey",
        "childId": "child_id",
        "disableTriggerFunction": "resource_trigger_disable",
        "edge": "resource_edge",
        "edgeCache": "resource_edge_cache",
        "edgeCacheBackfill": "resource_edge_cache_backfill",
        "edgeCacheChildCompute": "resource_edge_cache_child_compute",
        "edgeCacheChildFkey": "resource_edge_cache_child_pkey",
        "edgeCacheChildIdIndex": "resource_edge_cache_child_id_index",
        "edgeCacheParentCompute": "resource_edge_cache_parent_compute",
        "edgeCacheParentFkey": "resource_edge_cache_parent_pkey",
        "edgeCacheParentIdIndex": "resource_edge_cache_parent_id_index",
        "edgeCachePkey": "resource_edge_cache_pkey",
        "edgeCacheView": "resource_edge_cache_view",
        "edgeChildIdIndex": "resource_edge_child_id_index",
        "edgeDeleteTrigger": "10_resource_edge_delete_trigger",
        "edgeDeleteTriggerFunction": "resource_edge_delete_trigger_function",
        "edgeInsertTrigger": "10_resource_edge_insert_trigger",
        "edgeInsertTriggerFunction": "resource_edge_insert_trigger_function",
        "edgeParentIdIndex": "resource_edge_parent_id_index",
        "edgePkey": "resource_edge_pkey",
        "edgeUpdateTrigger": "10_resource_edge_update_trigger",
        "edgeUpdateTriggerFunction": "resource_edge_update_trigger_function",
        "enableTriggerFunction": "resource_trigger_enable",
        "id": "id",
        "name": "resource",
        "node": "resource_node",
        "nodeDeleteTrigger": "10_resource_node_delete_trigger",
        "nodeDeleteTriggerFunction": "resource_node_delete_trigger_function",
        "nodeInsertTrigger": "10_resource_node_insert_trigger",
        "nodeInsertTriggerFunction": "resource_node_insert_trigger_function",
        "nodeUpdateTrigger": "10_resource_node_update_trigger",
        "nodeUpdateTriggerFunction": "resource_node_update_trigger_function",
        "parentFkey": "resource_edge_parent_fkey",
        "parentId": "parent_id",
        "permission": "permission",
        "pkey": "resource_pkey",
        "varChildId": "var_child_id",
        "varParentId": "var_parent_id",
      },
      "reverse": "reverse",
      "role": {
        "childFkey": "role_edge_child_fkey",
        "childId": "child_id",
        "disableTriggerFunction": "role_trigger_disable",
        "edge": "role_edge",
        "edgeCache": "role_edge_cache",
        "edgeCacheBackfill": "role_edge_cache_backfill",
        "edgeCacheChildCompute": "role_edge_cache_child_compute",
        "edgeCacheChildFkey": "role_edge_cache_child_pkey",
        "edgeCacheChildIdIndex": "role_edge_cache_child_id_index",
        "edgeCacheParentCompute": "role_edge_cache_parent_compute",
        "edgeCacheParentFkey": "role_edge_cache_parent_pkey",
        "edgeCacheParentIdIndex": "role_edge_cache_parent_id_index",
        "edgeCachePkey": "role_edge_cache_pkey",
        "edgeCacheView": "role_edge_cache_view",
        "edgeChildIdIndex": "role_edge_child_id_index",
        "edgeDeleteTrigger": "10_role_edge_delete_trigger",
        "edgeDeleteTriggerFunction": "role_edge_delete_trigger_function",
        "edgeInsertTrigger": "10_role_edge_insert_trigger",
        "edgeInsertTriggerFunction": "role_edge_insert_trigger_function",
        "edgeParentIdIndex": "role_edge_parent_id_index",
        "edgePkey": "role_edge_pkey",
        "edgeUpdateTrigger": "10_role_edge_update_trigger",
        "edgeUpdateTriggerFunction": "role_edge_update_trigger_function",
        "enableTriggerFunction": "role_trigger_enable",
        "id": "id",
        "name": "role",
        "node": "role_node",
        "nodeDeleteTrigger": "10_role_node_delete_trigger",
        "nodeDeleteTriggerFunction": "role_node_delete_trigger_function",
        "nodeInsertTrigger": "10_role_node_insert_trigger",
        "nodeInsertTriggerFunction": "role_node_insert_trigger_function",
        "nodeUpdateTrigger": "10_role_node_update_trigger",
        "nodeUpdateTriggerFunction": "role_node_update_trigger_function",
        "parentFkey": "role_edge_parent_fkey",
        "parentId": "parent_id",
        "permission": "permission",
        "pkey": "role_pkey",
        "varChildId": "var_child_id",
        "varParentId": "var_parent_id",
      },
      "schema": "public",
      "select": "select",
      "tables": {
        "blog_post": {
          "name": "blog_post",
          "permission": {
            "user1": {
              "delete": "blog_post_user1_delete_policy",
              "insert": "blog_post_user1_insert_policy",
              "select": "blog_post_user1_select_policy",
              "update": "blog_post_user1_update_policy",
            },
          },
          "resourceFkey": "resource_blog_post_fkey",
          "resourceId": "resource_id",
          "roleFkey": "role_blog_post_fkey",
          "roleId": "role_id",
          "schema": "public",
        },
        "human_user": {
          "name": "human_user",
          "permission": {},
          "resourceFkey": "resource_human_user_fkey",
          "resourceId": "resource_id",
          "roleFkey": "role_human_user_fkey",
          "roleId": "role_id",
          "schema": "public",
        },
      },
      "trigger": "trigger",
      "update": "update",
      "var": "var",
      "view": "view",
    }
  `);
});