import type { Config } from "@p9s/core";
import { getCompleteConfig } from "@p9s/core";
import { createMigrationSql, expectedMigrationRecord } from "./generation.ts";

// The migration of a config as a migration of the tool of a stack, so that p9s runs with the other migrations of the
// app: in their order, in a transaction, recorded as they are.
export const migrationFormats = ["alembic", "django", "rails", "goose", "sqlx", "ecto", "laravel"] as const;
export type MigrationFormat = (typeof migrationFormats)[number];

export interface MigrationFileOptions {
  // The migration this one comes after: the revision of Alembic, like 0001, or app_label.name for Django, like
  // documents.0001_initial. Both tools need it.
  previous?: string;
  // The module the migration module of Ecto is in, like MyApp.Repo.Migrations
  module?: string;
  // The time of the timestamp of the file name, now by default
  now?: Date;
}

export interface MigrationFile {
  fileName: string;
  content: string;
}

// The folder where each tool keeps its migrations, by convention
export const migrationDirectories: Record<MigrationFormat, string> = {
  alembic: "migrations/versions",
  django: "migrations",
  rails: "db/migrate",
  goose: "migrations",
  sqlx: "migrations",
  ecto: "priv/repo/migrations",
  laravel: "database/migrations",
};

const quoteIdentifier = (name: string) => `"${name.replaceAll('"', '""')}"`;
const quoteLiteral = (value: string) => `'${value.replaceAll("'", "''")}'`;

// The users and graph writers of the config that do not exist yet, as p9s postgres migrate creates them: roles without
// login, granted to the role that runs the migration, so that it can act as them, and JIT off for users
export const createRolesSql = <User extends string>(config: Config<User>) => {
  const { engine } = getCompleteConfig(config);
  const roles = [...new Set<string>([...engine.users, ...engine.graphWriters])];
  if (roles.length === 0) return "";
  const creations = roles.map(role => `  if not exists (select from pg_roles where rolname = ${quoteLiteral(role)}) then
    create role ${quoteIdentifier(role)} nologin;
    grant ${quoteIdentifier(role)} to current_user;${(engine.users as string[]).includes(role) ? `
    alter role ${quoteIdentifier(role)} set jit = off;` : ""}
  end if;`);
  return `-- The users and graph writers of the config, created as p9s postgres migrate creates them
do $$
begin
${creations.join("\n")}
end
$$;
`;
};

const pad = (value: number, length = 2) => String(value).padStart(length, "0");
const timestamp = (date: Date, separator = "") =>
  [`${date.getUTCFullYear()}`, pad(date.getUTCMonth() + 1), pad(date.getUTCDate())].join(separator) + separator +
  [pad(date.getUTCHours()), pad(date.getUTCMinutes()), pad(date.getUTCSeconds())].join("");
const capitalize = (word: string) => word.charAt(0).toUpperCase() + word.slice(1);

// A string literal that holds the text as it is, in a heredoc or a raw string, which must not hold its end
const holding = (sql: string, end: string, format: MigrationFormat) => {
  if (sql.includes(end)) throw new Error(`The migration holds ${end}, which ends the string of the ${format} migration`);
  return sql;
};

export const createMigrationFile = <User extends string>(config: Config<User>, format: MigrationFormat, options: MigrationFileOptions = {}): MigrationFile => {
  const { hash, version } = expectedMigrationRecord(config);
  const name = `p9s_${hash.slice(0, 8)}`;
  const now = options.now ?? new Date();
  const sql = `${createRolesSql(config)}${createMigrationSql(config).trim()}\n`;
  const about = `The migration of p9s ${version}, ${hash}, generated by p9s postgres generate --format ${format} from the config of p9s.
It is idempotent, and p9s postgres status tells whether a database ran it. When the config changes, generate a new one.`;
  const previous = () => {
    if (!options.previous) throw new Error(`--format ${format} needs the migration this one comes after, with --previous`);
    return options.previous;
  };

  switch (format) {
    case "sqlx":
      return { fileName: `${timestamp(now)}_${name}.sql`, content: `${about.replace(/^/gm, "-- ")}\n${sql}` };

    case "goose":
      return {
        fileName: `${timestamp(now)}_${name}.sql`,
        content: `${about.replace(/^/gm, "-- ")}
-- +goose Up
-- +goose StatementBegin
${holding(sql, "-- +goose", format)}-- +goose StatementEnd

-- +goose Down
-- The objects of p9s stay: the migration of a new config replaces them
`,
      };

    case "alembic": {
      const down = previous();
      // A raw string keeps the SQL as it is, and a cursor of the driver runs it whole, without the bind parameters of
      // SQLAlchemy
      return {
        fileName: `${timestamp(now)}_${name}.py`,
        content: `"""${about}"""

from alembic import op

revision = ${JSON.stringify(name)}
down_revision = ${JSON.stringify(down)}
branch_labels = None
depends_on = None


def upgrade() -> None:
    cursor = op.get_bind().connection.cursor()
    try:
        cursor.execute(SQL)
    finally:
        cursor.close()


def downgrade() -> None:
    """The objects of p9s stay: the migration of a new config replaces them"""


SQL = r'''${holding(sql, "'''", format)}'''
`,
      };
    }

    case "django": {
      const dependency = previous();
      const [app, migration] = dependency.split(".");
      if (!app || !migration) throw new Error(`--previous is app_label.migration_name for Django, like documents.0001_initial, got ${dependency}`);
      const number = /^(\d+)_/.exec(migration)?.[1];
      const fileName = number ? `${pad(Number(number) + 1, number.length)}_${name}.py` : `${name}.py`;
      // In a list, Django runs the SQL whole, rather than splitting it in statements with sqlparse
      return {
        fileName,
        content: `"""${about}"""

from django.db import migrations

SQL = r'''${holding(sql, "'''", format)}'''


class Migration(migrations.Migration):
    dependencies = [(${JSON.stringify(app)}, ${JSON.stringify(migration)})]

    operations = [migrations.RunSQL([SQL], reverse_sql=migrations.RunSQL.noop)]
`,
      };
    }

    case "rails":
      return {
        fileName: `${timestamp(now)}_${name}.rb`,
        content: `${about.replace(/^/gm, "# ")}
class P9s${capitalize(hash.slice(0, 8))} < ActiveRecord::Migration[7.0]
  def up
    execute <<-'P9S_SQL'
${holding(sql, "P9S_SQL", format)}    P9S_SQL
  end

  # The objects of p9s stay: the migration of a new config replaces them
  def down; end
end
`,
      };

    case "ecto": {
      const namespace = options.module ?? "Repo.Migrations";
      // Postgrex prepares a query, which holds one statement, but for a query of type text
      return {
        fileName: `${timestamp(now)}_${name}.exs`,
        content: `defmodule ${namespace}.P9s${capitalize(hash.slice(0, 8))} do
${about.replace(/^/gm, "  # ")}
  use Ecto.Migration

  def up do
    repo().query!(sql(), [], query_type: :text, log: false)
  end

  # The objects of p9s stay: the migration of a new config replaces them
  def down, do: :ok

  defp sql do
    ~S"""
${holding(sql, '"""', format)}"""
  end
end
`,
      };
    }

    case "laravel":
      return {
        fileName: `${timestamp(now, "_")}_${name}.php`,
        content: `<?php

${about.replace(/^/gm, "// ")}

use Illuminate\\Database\\Migrations\\Migration;
use Illuminate\\Support\\Facades\\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::unprepared(<<<'P9S_SQL'
${holding(sql, "P9S_SQL", format)}P9S_SQL);
    }

    // The objects of p9s stay: the migration of a new config replaces them
    public function down(): void
    {
    }
};
`,
      };
  }
};
