import { expect, describe, test, beforeEach, afterEach } from 'bun:test'
import { query as sql, identifier, raw, type SQL } from "pg-sql2";
import { setupTests } from '@p9s/postgres-testing';
import type { Config } from '@p9s/core';
import { createMigration } from '../generation';
import { createIdentity } from '../identity';
import { defaultResourceCache, type TestContext } from './helpers';

// An application adopts p9s with nothing but the migration: the server tells p9s the id of the user in its own users
// table, and the migration grants users what the config lets them do
describe('adoption', () => {
  const { setup, teardown, context } = setupTests();
  beforeEach(setup);
  afterEach(teardown);

  type Authentication = NonNullable<Config<string>["engine"]>["authentication"];
  const adoptionConfig = (ctx: TestContext, column = "id", authentication?: Authentication): Config<string> => ({
    engine: {
      resourceCache: defaultResourceCache,
      users: [ctx.database_user_username],
      authentication: authentication ?? { getCurrentUserId: "current_role_id", setting: "app.user_id", key: { table: "app_user", column } },
      grantPrivileges: true,
      permission: { bitmap: { size: 8, names: { read: 0, write: 1 } } },
    },
    tables: [
      { name: "app_user", isRole: true, roleId: "role_id" },
      { name: "team", isRole: true, roleId: "role_id" },
      { name: "folder", isResource: true, resourceId: "resource_id", permission: { [ctx.database_user_username]: { select: 0 } } },
      {
        name: "document", isResource: true, resourceId: "resource_id",
        resourceParent: { column: "folder_id", table: "folder", key: "id" },
        permission: { [ctx.database_user_username]: { select: 0, insert: 1, update: 1 } },
      },
    ],
    links: [
      { name: "team_member", kind: "role", parent: { column: "team_id", table: "team", key: "id" }, child: { column: "user_id", table: "app_user", key: "id" } },
      {
        name: "folder_share", kind: "assignment",
        resource: { column: "folder_id", table: "folder", key: "id" }, role: { column: "team_id", table: "team", key: "id" },
        permission: { column: "access", values: { viewer: ["read"], editor: ["read", "write"] } },
      },
      {
        name: "document_share", kind: "assignment",
        resource: { column: "document_id", table: "document", key: "id" }, role: { column: "user_id", table: "app_user", key: "id" },
        permission: ["read"],
        privileges: { [ctx.database_user_username]: ["select", "insert", "delete"] },
      },
    ],
  });

  // Tables as the application made them, without a grant to the role of the users
  const load = async (column = "id", authentication?: Authentication) => {
    await context.exec(sql`
      create table "app_user" ("id" serial primary key, "name" text not null unique);
      create table "team" ("id" serial primary key, "name" text not null);
      create table "team_member" ("team_id" integer not null references "team", "user_id" integer not null references "app_user", primary key ("team_id", "user_id"));
      create table "folder" ("id" serial primary key, "name" text not null);
      create table "folder_share" ("folder_id" integer not null references "folder", "team_id" integer not null references "team", "access" text not null, primary key ("folder_id", "team_id"));
      create table "document" ("id" integer generated by default as identity primary key, "folder_id" integer not null references "folder", "title" text not null);
      create table "document_share" ("document_id" integer not null references "document", "user_id" integer not null references "app_user", primary key ("document_id", "user_id"));
      insert into "app_user" ("name") values ('alice'), ('bob'), ('carol');
      insert into "team" ("name") values ('eng'), ('sales');
      insert into "team_member" values (1, 1), (2, 2);
      insert into "folder" ("name") values ('specs'), ('deals');
      insert into "folder_share" values (1, 1, 'editor'), (2, 2, 'viewer');
      insert into "document" ("folder_id", "title") values (1, 'plan'), (2, 'budget');`);
    await context.exec(createMigration(adoptionConfig(context, column, authentication)));
  };

  const asUser = async (key: string, statement: SQL, setting = "app.user_id") => {
    const results = await context.runTestQuery(sql`
      set local role ${identifier(context.database_user_username)};
      select set_config(${raw(`'${setting}'`)}, ${raw(`'${key}'`)}, true);
      ${statement}`);
    return results.at(-1) as any[];
  };
  const titlesOf = async (key: string, setting?: string) => (await asUser(key, sql`select "title" from "document" order by "title"`, setting)).map((row: { title: string }) => row.title);

  test('the setting holds the id of the user in the users table of the app', async () => {
    await load();
    expect(await titlesOf("1")).toEqual(["plan"]);
    expect(await titlesOf("2")).toEqual(["budget"]);
    expect(await titlesOf("3")).toEqual([]);
    expect(await titlesOf("")).toEqual([]);
    expect(await titlesOf("42")).toEqual([]);
  });

  test('the key can be a column of any type', async () => {
    await load("name");
    expect(await titlesOf("alice")).toEqual(["plan"]);
    expect(await titlesOf("bob")).toEqual(["budget"]);
    expect(await titlesOf("nobody")).toEqual([]);
  });

  test('the setting can hold JSON claims, as PostgREST sets them from the JWT', async () => {
    const authentication = { getCurrentUserId: "current_role_id", setting: "request.jwt.claims", claim: "user_id", key: { table: "app_user", column: "id" } };
    await load("id", authentication);
    const claims = (value: object) => JSON.stringify({ sub: "8c5e", role: context.database_user_username, ...value });
    expect(await titlesOf(claims({ user_id: 1 }), "request.jwt.claims")).toEqual(["plan"]);
    expect(await titlesOf(claims({ user_id: "2" }), "request.jwt.claims")).toEqual(["budget"]);
    expect(await titlesOf(claims({}), "request.jwt.claims")).toEqual([]);
    expect(await titlesOf("", "request.jwt.claims")).toEqual([]);
    // A server that connects directly sets the same claims
    const { text, values } = createIdentity(adoptionConfig(context, "id", authentication)).statement(2);
    expect(values).toEqual(["role", context.database_user_username, "request.jwt.claims", '{"user_id":"2"}']);
    const results = await context.runTestQuery(sql`${raw(text.replace(/\$(\d+)/g, (_, i) => `'${values[Number(i) - 1]}'`))}; select "title" from "document" order by "title"`);
    expect((results.at(-1) as Array<{ title: string }>).map(row => row.title)).toEqual(["budget"]);
  });

  test('a claim without a key holds the role id', async () => {
    await load("id", { getCurrentUserId: "current_role_id", setting: "request.jwt.claims", claim: "sub" });
    const [{ role_id }] = (await context.runTestQuery(sql`select "role_id" from "app_user" where "name" = 'alice'`)).at(-1) as [{ role_id: number }];
    expect(await titlesOf(JSON.stringify({ sub: String(role_id) }), "request.jwt.claims")).toEqual(["plan"]);
  });

  test('users run what the config lets them, with no other grant', async () => {
    await load();
    // Inserting takes the sequence of the identity column
    await asUser("1", sql`insert into "document" ("folder_id", "title") values (1, 'roadmap')`);
    expect(await titlesOf("1")).toEqual(["plan", "roadmap"]);
    await expect(asUser("2", sql`insert into "document" ("folder_id", "title") values (2, 'forecast')`)).rejects.toThrow(/row-level security/);
    // Sharing through the link table its privileges name, with the bits the user has
    await asUser("1", sql`insert into "document_share" values (1, 3)`);
    expect(await titlesOf("3")).toEqual(["plan"]);
    await expect(asUser("1", sql`insert into "document_share" values (2, 3)`)).rejects.toThrow(/only give bits/);
    // Delete is not in the permissions of document, nor update in the privileges of document_share
    await expect(asUser("1", sql`delete from "document" where "title" = 'plan'`)).rejects.toThrow(/permission denied/);
    await expect(asUser("1", sql`update "document_share" set "user_id" = 2`)).rejects.toThrow(/permission denied/);
  });

  test('the key needs a setting and a role table, and the claim a setting', () => {
    const config = adoptionConfig(context);
    const withAuthentication = (authentication: NonNullable<Config<string>["engine"]>["authentication"]) => ({ ...config, engine: { ...config.engine, authentication } });
    expect(() => createMigration(withAuthentication({ getCurrentUserId: "uid", key: { table: "app_user", column: "id" } }))).toThrow(/needs a setting/);
    expect(() => createMigration(withAuthentication({ getCurrentUserId: "uid", setting: "app.user_id", key: { table: "folder", column: "id" } }))).toThrow(/not a role table/);
    expect(() => createMigration(withAuthentication({ getCurrentUserId: "uid", claim: "sub" }))).toThrow(/claim needs a setting/);
  });
});
